version: '3.8'

services:
  tts-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tts-app
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: ["npm", "start"]
