version: '3.8'

services:
  tts-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tts-app
    ports:
      - "3000:3000"
    restart: always
    # НЕ монтируем исходники в production, uncom для local
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    working_dir: /app
    command: ["npm", "start"]
